In [2]:
import numpy as  np
import pandas as pd



from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(["сжать руку", "разжать руку"])


#data['gesture'] = le.transform(data['gesture'])

LabelEncoder()

In [5]:
data_t = pd.read_csv("full_data_shuffle_24_04_2997.csv")
data = data_t
data.columns = ['sample_num', str(0), str(1), str(2), str(3), str(4), str(5),str(6),str(7),str(8),str(9),str(10),str(11),str(12),str(13), 'gesture']
data_t = pd.read_csv("data_train_new_appr_5 (1).csv")
data_t.columns = ['sample_num', str(0), str(1), str(2), str(3), str(4), str(5),str(6),str(7),str(8),str(9),str(10),str(11),str(12),str(13), 'gesture']
data_t['sample_num'] = data_t['sample_num']+len(data['sample_num'].unique())+1
data = data.append(data_t)
data.to_csv('full_data_shuffle.csv')
data[ data['gesture'] == 0].to_csv('data_0_({}).csv'.format(data[ data['gesture'] == 0].shape[0]))
data[ data['gesture'] == 1].to_csv('data_1_({}).csv'.format(data[ data['gesture'] == 1].shape[0]))

In [3]:
data_t = pd.read_csv("./Data_shuffle/data_train_1.csv")
data = data_t
data.columns = ['sample_num', str(0), str(1), str(2), str(3), str(4), str(5),str(6),str(7),str(8),str(9),str(10),str(11),str(12),str(13), 'gesture']
data_t = pd.read_csv("./Data_shuffle/data_train_2.csv")
data_t.columns = ['sample_num', str(0), str(1), str(2), str(3), str(4), str(5),str(6),str(7),str(8),str(9),str(10),str(11),str(12),str(13), 'gesture']
data_t['sample_num'] = data_t['sample_num']+len(data['sample_num'].unique())+1
data = data.append(data_t)
data_t = pd.read_csv("./Data_shuffle/data_train_3.csv")
data_t.columns = ['sample_num', str(0), str(1), str(2), str(3), str(4), str(5),str(6),str(7),str(8),str(9),str(10),str(11),str(12),str(13), 'gesture']
data_t['sample_num'] = data_t['sample_num']+len(data['sample_num'].unique())+1
data = data.append(data_t)
data_t = pd.read_csv("./Data_shuffle/data_train_4.csv")
data_t.columns = ['sample_num', str(0), str(1), str(2), str(3), str(4), str(5),str(6),str(7),str(8),str(9),str(10),str(11),str(12),str(13), 'gesture']
data_t['sample_num'] = data_t['sample_num']+len(data['sample_num'].unique())+1
data = data.append(data_t)
data_t = pd.read_csv("./Data_shuffle/data_train_5.csv")
data_t.columns = ['sample_num', str(0), str(1), str(2), str(3), str(4), str(5),str(6),str(7),str(8),str(9),str(10),str(11),str(12),str(13), 'gesture']
data_t['sample_num'] = data_t['sample_num']+len(data['sample_num'].unique())+1
data = data.append(data_t)

data_t = pd.read_csv("./Data_shuffle/data_train_6.csv")
data_t.columns = ['sample_num', str(0), str(1), str(2), str(3), str(4), str(5),str(6),str(7),str(8),str(9),str(10),str(11),str(12),str(13), 'gesture']
data_t['sample_num'] = data_t['sample_num']+len(data['sample_num'].unique())+1
data = data.append(data_t)
data_t = pd.read_csv("./Data_shuffle/data_train_7.csv")
data_t.columns = ['sample_num', str(0), str(1), str(2), str(3), str(4), str(5),str(6),str(7),str(8),str(9),str(10),str(11),str(12),str(13), 'gesture']
data_t['sample_num'] = data_t['sample_num']+len(data['sample_num'].unique())+1
data = data.append(data_t)
data_t = pd.read_csv("./Data_shuffle/data_train_8.csv")
data_t.columns = ['sample_num', str(0), str(1), str(2), str(3), str(4), str(5),str(6),str(7),str(8),str(9),str(10),str(11),str(12),str(13), 'gesture']
data_t['sample_num'] = data_t['sample_num']+len(data['sample_num'].unique())+1
data = data.append(data_t)
data_t = pd.read_csv("./Data_shuffle/data_train_9.csv")
data_t.columns = ['sample_num', str(0), str(1), str(2), str(3), str(4), str(5),str(6),str(7),str(8),str(9),str(10),str(11),str(12),str(13), 'gesture']
data_t['sample_num'] = data_t['sample_num']+len(data['sample_num'].unique())+1
data = data.append(data_t)
data_r = data[data['gesture'] == "сжать руку"] 
data_r = data_r.append(data[data['gesture'] == "разжать руку"])
data = data_r
data.to_csv('full_data_shuffle.csv')
data

,sample_num,0,1,2,3,4,5,6,7,8,9,10,11,12,13,gesture
0,0,4178.077,4193.462,4197.179,4189.487,4198.974,4191.923,4203.846,4196.410,4207.436,4206.538,4193.333,4238.846,4188.846,4204.744,сжать руку
1,0,4185.641,4192.179,4203.462,4194.359,4209.615,4199.103,4206.795,4200.513,4210.897,4213.205,4207.692,4246.410,4204.744,4216.795,сжать руку
2,0,4187.051,4203.974,4203.846,4201.538,4205.641,4205.513,4216.795,4203.846,4206.667,4207.692,4217.949,4249.103,4212.308,4223.333,сжать руку
3,0,4180.641,4200.769,4198.077,4202.564,4202.436,4193.333,4203.846,4202.821,4203.077,4198.590,4205.385,4241.667,4201.538,4211.795,сжать руку
4,0,4184.615,4198.974,4203.333,4208.718,4208.462,4200.641,4202.564,4205.641,4212.564,4210.000,4199.744,4247.692,4200.769,4210.897,сжать руку
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7495,624,4188.462,4199.744,4197.564,4197.949,4195.641,4222.692,4199.744,4190.897,4203.333,4205.641,4212.692,4187.051,4197.436,4205.385,разжать руку
7496,624,4183.718,4199.359,4196.795,4193.974,4187.051,4214.615,4189.872,4187.949,4200.000,4206.282,4203.462,4180.000,4197.051,4208.333,разжать руку
7497,624,4187.692,4204.359,4200.385,4194.359,4181.026,4218.974,4196.795,4191.538,4206.538,4226.026,4205.256,4189.487,4216.154,4212.436,разжать руку
7498,624,4186.667,4199.487,4202.821,4192.564,4184.103,4222.692,4207.051,4200.769,4218.462,4234.231,4218.462,4194.615,4209.359,4208.846,разжать руку
7499,624,4182.692,4183.462,4201.795,4186.154,4177.308,4212.308,4200.769,4199.103,4212.436,4215.128,4215.256,4182.436,4183.333,4204.103,разжать руку

In [29]:
N=10
nums = [[0 for i in range(N)]]
for i in range(1,int(100/N)):
    nums.append([i for j in range(N)])
    nums
nums = np.array(nums).reshape((-1,))
rebuild_data = []
for sample in data['sample_num'].unique():
    names_list = []
    sample_by_data = data[data['sample_num'] == sample]
    sample_by_data['sub_period'] = nums
    accs = pd.Series()
    for part in sample_by_data['sub_period'].unique():
        part_data = sample_by_data[sample_by_data['sub_period']==part]
        for i in range(14):
            accs['mean_'+str(i)+"_"+str(part)] = part_data[str(i)].mean(axis = 0)
            accs['min_'+str(i)+"_"+str(part)] = part_data[str(i)].min(axis = 0)
            accs['max_'+str(i)+"_"+str(part)] = part_data[str(i)].max(axis = 0)
            names_list.append('mean_'+str(i)+"_"+str(part))
            names_list.append('min_'+str(i)+"_"+str(part))
            names_list.append('max_'+str(i)+"_"+str(part))
    names_list.append('gesture')
    accs['gesture'] = sample_by_data['gesture'].unique()[0]
    rebuild_data.append(accs.values)
rebuild_data = pd.DataFrame(rebuild_data)
rebuild_data.columns = names_list
rebuild_data
rebuild_data['gesture'] = le.transform(rebuild_data['gesture'])

/home/pavel/.local/lib/python3.6/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()

In [30]:
rebuild_data.to_csv('full_data_transformed_shuffle.csv')

In [31]:
X = rebuild_data.drop(['gesture'], axis = 1)
y = rebuild_data['gesture']
X

,mean_0_0,min_0_0,max_0_0,mean_1_0,min_1_0,max_1_0,mean_2_0,min_2_0,max_2_0,mean_3_0,...,max_10_9,mean_11_9,min_11_9,max_11_9,mean_12_9,min_12_9,max_12_9,mean_13_9,min_13_9,max_13_9
0,4179.1025,4167.308,4187.051,4194.2307,4177.821,4203.974,4200.2436,4193.333,4204.231,4198.1024,...,4230.641,4250.8461,4236.667,4258.333,4237.1409,4215.128,4243.333,4221.8206,4203.462,4231.026
1,4198.8719,4189.103,4209.872,4100.8974,4090.513,4113.205,4225.3334,4218.590,4232.179,4169.7948,...,4247.564,4242.3974,4224.615,4262.308,4212.4617,4182.949,4231.667,4189.9744,4168.333,4212.692
2,4252.4357,4206.410,4277.179,4252.8588,4199.615,4281.154,4209.6923,4187.949,4221.410,4223.6155,...,4232.436,4246.4616,4227.821,4264.487,4201.7949,4183.590,4221.282,4198.9358,4178.205,4215.897
3,4196.5897,4189.103,4205.128,4217.5898,4206.282,4230.385,4199.9744,4192.436,4210.513,4199.5641,...,4244.231,4256.8461,4245.897,4270.897,4217.1795,4204.103,4231.154,4214.2563,4203.974,4228.718
4,4216.5385,4211.282,4230.000,4250.7693,4243.333,4258.077,4173.7307,4165.769,4177.821,4200.6281,...,4202.692,4224.4102,4210.641,4242.179,4162.3590,4146.667,4177.949,4183.6411,4164.359,4201.410
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
274,4190.8077,4181.282,4196.026,4184.7306,4174.744,4203.077,4169.9231,4164.231,4174.744,4187.0001,...,4209.359,4196.8716,4189.615,4206.538,4185.0512,4175.256,4193.846,4228.0256,4221.538,4239.103
275,4205.5129,4198.846,4214.872,4186.2179,4177.821,4192.692,4187.5769,4178.846,4192.179,4194.7565,...,4216.026,4224.6283,4210.000,4240.000,4196.9103,4182.949,4208.077,4210.2693,4198.718,4221.667
276,4194.1796,4190.128,4197.436,4212.3591,4198.718,4223.077,4198.5129,4190.000,4205.769,4210.5771,...,4230.256,4221.9744,4214.231,4232.692,4208.7309,4204.872,4213.462,4200.9231,4196.667,4207.436
277,4175.2656,4167.436,4184.231,4198.0952,4192.051,4203.974,4193.3314,4188.205,4202.051,4199.6300,...,4258.718,4219.0385,4209.231,4224.487,4195.0256,4184.744,4205.769,4194.7821,4186.795,4199.231
278,4202.1025,4193.846,4210.641,4205.2179,4198.974,4212.564,4205.0257,4198.077,4212.564,4197.3462,...,4193.077,4222.6666,4215.385,4226.282,4202.1026,4198.333,4206.795,4193.9487,4190.641,4200.000

In [32]:
from sklearn.model_selection import train_test_split

X_train,  X_control, y_train, y_control = train_test_split(X, y, shuffle = True, test_size=0.1)

In [54]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
clf = RandomForestClassifier()
scores = cross_val_score(clf, X_train, y_train, cv=10)

In [55]:
scores

array([0.5 , 0.4 , 0.48, 0.4 , 0.4 , 0.4 , 0.52, 0.48, 0.4 , 0.28])

In [57]:
from sklearn.metrics import accuracy_score
clf.fit(X_train, y_train)
print("Score is {}".format(accuracy_score(y_control, clf.predict(X_control))))

Score is 0.2857142857142857

In [60]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import cross_val_score
clf = GradientBoostingClassifier()
scores = cross_val_score(clf, X_train, y_train, cv=10)
scores

array([0.53846154, 0.4       , 0.44      , 0.4       , 0.4       ,
       0.36      , 0.52      , 0.32      , 0.28      , 0.44      ])

In [59]:
from sklearn.metrics import accuracy_score
clf.fit(X_train, y_train)
print("Score is {}".format(accuracy_score(y_control, clf.predict(X_control))))

Score is 0.21428571428571427

In [68]:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import cross_val_score
clf = MLPClassifier(hidden_layer_sizes = [10,50,100, 200, 100, 50, 100, 200, 300,200, 100, 50, 100, 200, 300, 400, 500,1000,800, 500,600,300,50,12,])
scores = cross_val_score(clf, X_train, y_train, cv=10)
scores

array([0.53846154, 0.56      , 0.52      , 0.52      , 0.52      ,
       0.52      , 0.52      , 0.48      , 0.52      , 0.52      ])

In [69]:
from sklearn.metrics import accuracy_score
clf.fit(X_train, y_train)
print("Score is {}".format(accuracy_score(y_control, clf.predict(X_control))))

Score is 0.32142857142857145

In [227]:
import pickle

clf.fit(X, y)
with open('rfc_4_04.pickle', 'wb') as f:
    pickle.dump(clf, f)

with open('label_encoder_4_04.pickle', 'wb') as f:
    pickle.dump(le, f)
    
with open('data_4_04.pickle', 'wb') as f:
    pickle.dump(data, f)

In [209]:
estimator = clf

def transform_predict(eeg_data,est, le):
    N=10
    nums = [[0 for i in range(N)]]
    for i in range(1,int(100/N)):
        nums.append([i for j in range(N)])
        nums
    nums = np.array(nums).reshape((-1,))
    rebuild_data = []
    names_list = []
    sample_by_data = eeg_data
    sample_by_data['sub_period'] = nums
    accs = pd.Series()
    for part in eeg_data['sub_period'].unique():
        part_data = sample_by_data[sample_by_data['sub_period']==part]
        for i in range(14):
            accs['mean_'+str(i)+"_"+str(part)] = part_data[str(i)].mean(axis = 0)
            accs['min_'+str(i)+"_"+str(part)] = part_data[str(i)].min(axis = 0)
            accs['max_'+str(i)+"_"+str(part)] = part_data[str(i)].max(axis = 0)
            names_list.append('mean_'+str(i)+"_"+str(part))
            names_list.append('min_'+str(i)+"_"+str(part))
            names_list.append('max_'+str(i)+"_"+str(part))
    rebuild_data.append(accs.values)
    rebuild_data = pd.DataFrame(rebuild_data)
    rebuild_data.columns = names_list
    return le.inverse_transform(est.predict(rebuild_data))

In [226]:
func_test_sample = data[data['sample_num'] ==300]
func_test_sample = func_test_sample.drop(['sample_num'], axis = 1)

transform_predict(func_test_sample, le)

array(['0_1'], dtype='<U3')