In [193]:
import numpy as  np
import pandas as pd

data = pd.read_csv("full_data.csv")
data.columns = ['sample_num', str(0), str(1), str(2), str(3), str(4), str(5),str(6),str(7),str(8),str(9),str(10),str(11),str(12),str(13), 'gesture']
data
from sklearn.preprocessing import LabelEncoder()
le = preprocessing.LabelEncoder()
le.fit(["0_1", "1_0"])


#data['gesture'] = le.transform(data['gesture'])

LabelEncoder()

In [194]:
data_0_1 = data[data['gesture'] == '0_1']
data_1_0 = data[data['gesture'] == '1_0']
data_0_1['sample_num'] = data_0_1['sample_num']+len(data_1_0['sample_num'].unique())+1
data = pd.concat([data_1_0, data_0_1], axis = 0)
data_1_0

/home/pavel/.local/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

,sample_num,0,1,2,3,4,5,6,7,8,9,10,11,12,13,gesture
0,0,4179.359,3801.795,4181.667,4193.205,4206.154,4190.000,4197.179,4174.615,4172.179,4197.436,4180.769,4135.897,4168.590,4175.385,1_0
1,0,4192.436,3808.974,4187.949,4196.795,4215.897,4200.256,4206.154,4185.385,4188.718,4205.513,4205.769,4158.077,4194.487,4193.974,1_0
2,0,4189.872,3801.154,4184.744,4192.564,4192.564,4192.949,4203.077,4187.821,4174.744,4192.179,4215.769,4160.897,4198.462,4199.872,1_0
3,0,4186.026,3800.000,4185.641,4194.103,4211.538,4193.718,4203.974,4187.949,4176.282,4205.000,4205.641,4157.692,4193.205,4199.487,1_0
4,0,4197.051,3815.000,4192.179,4207.051,4245.769,4211.795,4216.667,4195.769,4212.949,4233.974,4211.923,4168.846,4199.615,4204.615,1_0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20395,204,4203.590,4204.744,4203.333,4212.564,4203.077,4200.256,4210.385,4194.359,4189.872,4197.821,4196.026,4178.333,4192.436,4201.923,1_0
20396,204,4204.744,4203.718,4208.718,4209.103,4200.513,4202.436,4196.410,4196.026,4192.949,4206.795,4206.538,4184.487,4204.103,4207.051,1_0
20397,204,4204.359,4203.718,4209.103,4203.462,4197.949,4201.154,4198.718,4197.308,4205.000,4211.538,4212.821,4183.077,4210.897,4205.256,1_0
20398,204,4201.795,4199.103,4203.718,4205.000,4191.282,4200.000,4206.923,4195.769,4195.256,4203.974,4204.615,4174.487,4205.897,4201.667,1_0
20399,204,4203.462,4199.872,4206.282,4208.974,4200.769,4198.333,4199.744,4204.103,4190.128,4207.949,4206.923,4181.667,4207.692,4206.923,1_0

In [195]:
data_0_1

,sample_num,0,1,2,3,4,5,6,7,8,9,10,11,12,13,gesture
20400,205,4237.564,4228.205,4200.897,4198.590,4190.256,4188.205,4190.513,4200.000,4178.077,4205.769,4212.949,4194.615,4164.103,4202.564,0_1
20401,205,4237.564,4242.564,4197.821,4211.154,4211.282,4185.385,4193.205,4190.256,4166.410,4194.231,4207.308,4191.282,4158.205,4197.436,0_1
20402,205,4242.821,4246.282,4204.744,4216.667,4229.872,4213.077,4211.667,4200.641,4177.308,4189.103,4209.103,4200.256,4160.128,4201.538,0_1
20403,205,4257.821,4269.103,4217.949,4231.154,4244.744,4232.436,4219.744,4221.154,4204.744,4217.949,4224.744,4215.513,4189.359,4217.436,0_1
20404,205,4258.205,4273.205,4218.333,4237.179,4244.744,4232.821,4218.462,4227.949,4209.103,4226.923,4226.154,4216.410,4196.923,4218.333,0_1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40395,407,4193.718,4208.205,4210.513,4206.154,4195.128,4216.410,4210.128,4204.872,4200.897,4177.692,4207.179,4195.641,4213.077,4204.103,0_1
40396,407,4191.667,4205.641,4207.821,4204.231,4174.872,4205.769,4207.949,4205.128,4200.769,4177.179,4207.949,4189.744,4214.359,4200.513,0_1
40397,407,4178.205,4192.308,4198.846,4192.692,4160.128,4207.692,4206.795,4211.282,4203.590,4181.538,4202.051,4185.256,4205.128,4193.462,0_1
40398,407,4171.795,4182.308,4192.179,4190.128,4168.718,4215.897,4208.590,4216.282,4203.718,4175.769,4192.436,4181.538,4190.256,4188.205,0_1
40399,407,4172.949,4178.590,4192.692,4191.154,4172.436,4210.897,4208.462,4211.795,4202.308,4162.692,4188.333,4173.462,4187.179,4189.359,0_1

In [196]:
N=10
nums = [[0 for i in range(N)]]
for i in range(1,int(100/N)):
    nums.append([i for j in range(N)])
    nums
nums = np.array(nums).reshape((-1,))
rebuild_data = []
for sample in data['sample_num'].unique():
    names_list = []
    sample_by_data = data[data['sample_num'] == sample]
    sample_by_data['sub_period'] = nums
    accs = pd.Series()
    for part in sample_by_data['sub_period'].unique():
        part_data = sample_by_data[sample_by_data['sub_period']==part]
        for i in range(14):
            accs['mean_'+str(i)+"_"+str(part)] = part_data[str(i)].mean(axis = 0)
            accs['min_'+str(i)+"_"+str(part)] = part_data[str(i)].min(axis = 0)
            accs['max_'+str(i)+"_"+str(part)] = part_data[str(i)].max(axis = 0)
            names_list.append('mean_'+str(i)+"_"+str(part))
            names_list.append('min_'+str(i)+"_"+str(part))
            names_list.append('max_'+str(i)+"_"+str(part))
    names_list.append('gesture')
    accs['gesture'] = sample_by_data['gesture'].unique()[0]
    rebuild_data.append(accs.values)
rebuild_data = pd.DataFrame(rebuild_data)
rebuild_data.columns = names_list
rebuild_data
rebuild_data['gesture'] = le.transform(rebuild_data['gesture'])

/home/pavel/.local/lib/python3.6/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()

In [197]:
rebuild_data.to_csv('full_data_transformed.csv')

In [199]:
X = rebuild_data.drop(['gesture'], axis = 1)
y = rebuild_data['gesture']
X

,mean_0_0,min_0_0,max_0_0,mean_1_0,min_1_0,max_1_0,mean_2_0,min_2_0,max_2_0,mean_3_0,...,max_10_9,mean_11_9,min_11_9,max_11_9,mean_12_9,min_12_9,max_12_9,mean_13_9,min_13_9,max_13_9
0,4191.7564,4179.359,4198.077,3805.2308,3791.410,3815.256,4187.3078,4181.667,4192.821,4197.8718,...,4188.718,4122.7565,4108.462,4142.821,4077.3333,4050.256,4101.282,4193.9873,4176.795,4214.103
1,4169.4359,4161.026,4183.333,3746.1795,3719.231,3792.692,4172.6411,4167.821,4177.692,4174.9103,...,4219.487,4215.3460,4205.513,4237.051,4240.3333,4218.846,4280.641,4203.1411,4193.846,4218.718
2,4204.2181,4189.359,4224.744,4296.9231,4122.179,4475.513,4177.4872,4170.897,4184.231,4173.4614,...,4207.564,4271.2436,4260.128,4285.256,4170.0256,4159.872,4182.949,4205.3975,4192.179,4219.487
3,4237.4615,4226.923,4259.744,4299.8719,4284.231,4323.974,4216.6922,4208.846,4228.205,4242.0770,...,4239.872,4199.8205,4189.744,4219.872,4230.6153,4221.923,4244.359,4221.2308,4214.487,4234.231
4,4213.4615,4206.667,4220.897,4300.8716,4291.923,4307.692,4211.4359,4202.949,4216.923,4211.4743,...,4231.026,4178.8720,4165.513,4198.846,4228.4361,4218.590,4242.308,4211.3718,4201.154,4226.282
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
399,4202.1411,4197.308,4206.026,4208.7821,4201.923,4220.385,4211.7435,4208.077,4217.692,4211.2052,...,4212.051,4196.5129,4186.923,4203.205,4195.3333,4191.026,4202.179,4205.1539,4202.821,4211.282
400,4224.4231,4221.154,4228.590,4209.7307,4205.000,4219.615,4211.5897,4205.128,4223.718,4227.8974,...,4277.821,4234.5514,4217.436,4249.615,4301.4103,4236.923,4381.923,4243.2179,4218.718,4262.436
401,4252.3846,4235.513,4282.051,4199.0770,4174.744,4232.564,4218.8075,4209.615,4226.282,4211.3975,...,4204.103,4205.4231,4200.000,4217.051,4185.9871,4178.590,4197.179,4205.0128,4199.872,4213.846
402,4244.6924,4196.026,4284.359,4279.0130,4220.513,4331.667,4220.4231,4202.821,4236.795,4237.0770,...,4212.308,4200.6409,4194.487,4203.333,4166.0511,4155.897,4181.282,4198.0129,4191.667,4202.179
403,4190.2565,4182.308,4197.308,4208.3717,4193.590,4214.615,4193.3461,4189.359,4198.205,4197.5770,...,4207.949,4184.9231,4173.462,4195.641,4198.4614,4186.923,4214.359,4194.9104,4188.205,4204.103

In [218]:
from sklearn.model_selection import train_test_split

X_train,  X_control, y_train, y_control = train_test_split(X, y, shuffle = True, test_size=0.1)

In [219]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
clf = RandomForestClassifier()
scores = cross_val_score(clf, X_train, y_train, cv=10)

In [220]:
scores

array([0.94594595, 0.97297297, 0.89189189, 0.94444444, 0.75      ,
       0.88888889, 0.88888889, 0.91666667, 0.77777778, 0.94444444])

In [217]:
from sklearn.metrics import accuracy_score
clf.fit(X_train, y_train)
print("Score is {}".format(accuracy_score(y_control, clf.predict(X_control))))

Score is 0.8292682926829268

In [227]:
import pickle

clf.fit(X, y)
with open('rfc_4_04.pickle', 'wb') as f:
    pickle.dump(clf, f)

with open('label_encoder_4_04.pickle', 'wb') as f:
    pickle.dump(le, f)
    
with open('data_4_04.pickle', 'wb') as f:
    pickle.dump(data, f)

In [209]:
estimator = clf

def transform_predict(eeg_data,est, le):
    N=10
    nums = [[0 for i in range(N)]]
    for i in range(1,int(100/N)):
        nums.append([i for j in range(N)])
        nums
    nums = np.array(nums).reshape((-1,))
    rebuild_data = []
    names_list = []
    sample_by_data = eeg_data
    sample_by_data['sub_period'] = nums
    accs = pd.Series()
    for part in eeg_data['sub_period'].unique():
        part_data = sample_by_data[sample_by_data['sub_period']==part]
        for i in range(14):
            accs['mean_'+str(i)+"_"+str(part)] = part_data[str(i)].mean(axis = 0)
            accs['min_'+str(i)+"_"+str(part)] = part_data[str(i)].min(axis = 0)
            accs['max_'+str(i)+"_"+str(part)] = part_data[str(i)].max(axis = 0)
            names_list.append('mean_'+str(i)+"_"+str(part))
            names_list.append('min_'+str(i)+"_"+str(part))
            names_list.append('max_'+str(i)+"_"+str(part))
    rebuild_data.append(accs.values)
    rebuild_data = pd.DataFrame(rebuild_data)
    rebuild_data.columns = names_list
    return le.inverse_transform(est.predict(rebuild_data))

In [226]:
func_test_sample = data[data['sample_num'] ==300]
func_test_sample = func_test_sample.drop(['sample_num'], axis = 1)

transform_predict(func_test_sample, le)

array(['0_1'], dtype='<U3')